name: Windows
on:
  push:
    paths-ignore:
      - 'doc/**'
      - '**/man/*'
      - '**.md'
      - '**.rdoc'
      - '**/.document'
      - '.*.yml'
  pull_request:
    # Do not use paths-ignore for required status checks
    # https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks
  merge_group:

concurrency:
  group: ${{ github.workflow }} / ${{ startsWith(github.event_name, 'pull') && github.ref_name || github.sha }}
  cancel-in-progress: ${{ startsWith(github.event_name, 'pull') }}

permissions:
  contents: read

jobs:
  make:
    # strategy:
    #   matrix:
    #     include:
    #       - vc: 2015
    #         vs: 2019
    #         vcvars: '10.0.14393.0 -vcvars_ver=14.0' # The oldest Windows 10 SDK w/ VC++ 2015 toolset (v140)
    #         test_task: check
    #       - vs: 2019
    #         test_task: check
    #       - vs: 2022
    #         test_task: check
    #       - vs: 2022
    #         test_task: test-bundled-gems
    #   fail-fast: false

    # runs-on: windows-${{ matrix.vs < 2022 && '2019' || matrix.vs }}
    runs-on: windows-2019

    if: >-
      ${{!(false
      || contains(github.event.head_commit.message, '[DOC]')
      || contains(github.event.head_commit.message, 'Document')
      || contains(github.event.pull_request.title, '[DOC]')
      || contains(github.event.pull_request.title, 'Document')
      || contains(github.event.pull_request.labels.*.name, 'Documentation')
      || (github.event_name == 'push' && github.event.pull_request.user.login == 'dependabot[bot]')
      )}}

    # name: VisualStudio ${{ matrix.vc || matrix.vs }} (${{ matrix.test_task }})
    name: VisualStudio

    env:
      GITPULLOPTIONS: --no-tags origin ${{ github.ref }}
      OS_VER: windows-2019
      VCPKG_DEFAULT_TRIPLET: x64-windows

    steps:
      - run: md build
        working-directory:

    #   - name: find tools
    #     id: find-tools
    #     run: |
    #       ::- find needed tools
    #       set NEEDS=
    #       for %%I in (%NEEDED_TOOLS%) do if "%%~$PATH:I" == "" (
    #         call set NEEDS=%%NEEDS%% %%~nI
    #       ) else (
    #         echo %%I: %%~$PATH:I
    #       )
    #       echo.needs=%NEEDS%>>%GITHUB_OUTPUT%
    #       if "%NEEDS%" == "" (
    #         echo [debug] All needed tools found
    #       ) else (
    #         echo [warning^]Needs%NEEDS%
    #       )
    #     env:
    #       NEEDED_TOOLS: >-
    #         patch.exe

      - uses: msys2/setup-msys2@d40200dc2db4c351366b048a9565ad82919e1c24 # v2
        id: setup-msys2
        with:
          update: true
          install: >-
            ${{ steps.find-tools.outputs.needs }}
        if: ${{ steps.find-tools.outputs.needs != '' }}

      - uses: ruby/setup-ruby@a6e6f86333f0a2523ece813039b8b4be04560854 # v1.190.0
        with:
          ruby-version: '3.0'
          bundler: none
          windows-toolchain: none
      - name: Run tests
        working-directory: build
        run: |
          dir
          bundle install
          bundle exec rspec scratch.rb